### ISSUE TITLE
README

### ISSUE THREAD

**Issue by cqvu** [MLH-Fellowship/MLPrep#19]
Make an awesome README for MLPrep

Example template: https://github.com/othneildrew/Best-README-Template/blob/master/BLANK_README.md

**Comment by cqvu** [comment]
@eamspoker oops I forgot to assign myself, I got this issue. I made a basic README but feel free to add more. I'll add screenshots once we have all the functionalities

**Comment by eamspoker** [comment]
@cqvu okay, awesome!
